# Generated by Django 5.0.4 on 2024-11-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='applied_on',
        ),
    ]
