# Generated by Django 5.0.4 on 2024-11-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
